services:
  gem-optimizer:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    image: macs-gem-optimizer:latest
    container_name: macs-gem-optimizer
    ports:
      - '0.0.0.0:8080:8080'
